/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories/index'
import { Route as ProvisioningIndexRouteImport } from './routes/provisioning/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as ModulesIndexRouteImport } from './routes/modules/index'
import { Route as InfrastructureIndexRouteImport } from './routes/infrastructure/index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as CompaniesNewRouteImport } from './routes/companies/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisioningIndexRoute = ProvisioningIndexRouteImport.update({
  id: '/provisioning/',
  path: '/provisioning/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureIndexRoute = InfrastructureIndexRouteImport.update({
  id: '/infrastructure/',
  path: '/infrastructure/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesNewRoute = CompaniesNewRouteImport.update({
  id: '/companies/new',
  path: '/companies/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies/new': typeof CompaniesNewRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/companies/': typeof CompaniesIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/provisioning/': typeof ProvisioningIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies/new': typeof CompaniesNewRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/companies': typeof CompaniesIndexRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/infrastructure': typeof InfrastructureIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/provisioning': typeof ProvisioningIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies/new': typeof CompaniesNewRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/companies/': typeof CompaniesIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/infrastructure/': typeof InfrastructureIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/provisioning/': typeof ProvisioningIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies/new'
    | '/projects/$slug'
    | '/companies/'
    | '/deployments/'
    | '/infrastructure/'
    | '/modules/'
    | '/plugins/'
    | '/projects/'
    | '/provisioning/'
    | '/repositories/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies/new'
    | '/projects/$slug'
    | '/companies'
    | '/deployments'
    | '/infrastructure'
    | '/modules'
    | '/plugins'
    | '/projects'
    | '/provisioning'
    | '/repositories'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/companies/new'
    | '/projects/$slug'
    | '/companies/'
    | '/deployments/'
    | '/infrastructure/'
    | '/modules/'
    | '/plugins/'
    | '/projects/'
    | '/provisioning/'
    | '/repositories/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesNewRoute: typeof CompaniesNewRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  InfrastructureIndexRoute: typeof InfrastructureIndexRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProvisioningIndexRoute: typeof ProvisioningIndexRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisioning/': {
      id: '/provisioning/'
      path: '/provisioning'
      fullPath: '/provisioning/'
      preLoaderRoute: typeof ProvisioningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure/': {
      id: '/infrastructure/'
      path: '/infrastructure'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof InfrastructureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/new': {
      id: '/companies/new'
      path: '/companies/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof CompaniesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesNewRoute: CompaniesNewRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  InfrastructureIndexRoute: InfrastructureIndexRoute,
  ModulesIndexRoute: ModulesIndexRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProvisioningIndexRoute: ProvisioningIndexRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
